### ISSUE TITLE
Json syntax issues 

### ISSUE THREAD

**Issue by kinggoesgaming** [Radical-Delta/MinersHandoutsWebAPI#6]
So today I ran a test for the get all json and the syntax still seems to be messy... Will add details later when I get on my computer

**Comment by turtledude01** [comment]
http://jsonlint.com/ Says the syntax is correct

**Comment by kinggoesgaming** [comment]
Alright now that I have access to a computer...

currently the `API/config/get/all.php` returns `[{"success":"true","Name":"l","Value":"ll"},{"success":"true","Name":"ll","Value":"Var2"}]`. 

However I see a major design flaw with this.

For starters we have unwanted success status for each item in the list. that's unwanted and wasted memory and eats traffic. This reduces the list to 

[{"Name":"l","Value":"ll"},{Name":"ll","Value":"Var2"}]

but now we dont have success indicator. This can not acceptable as the success indicator is important.
To remedy this I think a slight restructuring the JSON.

lets have have the JSON restructured as this: 

```json
{
    "success" : true,
    "payload" : {
       "all" : [
      {
        "Name":"l",
        "Value":"ll"
      },
      {
        "Name":"ll",
        "Value":"Var2"
      }
      ]
}
}
```

This organizes the json a bit. This stands true for every json string.. payload should be the one holding all the data.

**Comment by turtledude01** [comment]
My plan with the JSOn was to keep it clean and simple, having the success indicator is actually nice for each one as what would happen if the database suddenly broke or incorrect data was sent to it? With your idea, you will only know on the first step if the database is working, but on the rest you just have to trust it.  On the current setup, the database can fail on any of the different ones and tell you what went wrong.  Your plan would make error reporting almost impossible.

**Comment by kinggoesgaming** [comment]
the reason i want it structured in the payload cuz we build a organised structure.. it may look simple right now. That's cause we only have a few information bits. But we cant predict what data we will have in the future and restructuring later is going to be an issue, especially considering from an API point of view

**Comment by kinggoesgaming** [comment]
> having the success indicator is actually nice for each one as what would happen if the database suddenly broke or incorrect data was sent to it? 

how about the success being there in the front and each one recursively inside the payload...?

**Comment by turtledude01** [comment]
This is true, but then comes this problem that i stated before: If i do not supply the status with each database query, then the entire thing could break and potentially send invalid json entirely.

**Comment by turtledude01** [comment]
I will have to take a look at some things and test, for now it stays how it is.  I still have to restructure the API to work with the database

**Comment by turtledude01** [comment]
After thinking this over today, im going to be converting the entire API to a simpler json setup, the json will still be output in a similar fashion, but instead of me printing it out, i will be converted to a nice format and will allow me to force the first STATUS to default to FALSE if any of the conections fail. So, my question is this: Does printing the json like this work> [{"success":"true/false"},{"name":"this","value":"that"},{"name":"thats","value":"theis"}]

**Comment by kinggoesgaming** [comment]
@turtledude01 you dont understand... parsing a list json like that is harder... the format i gave may look obnoxious but it is easier than what we are doing right now

**Comment by kinggoesgaming** [comment]
think of this way: first i have to iterate through the list for finding the list item that holds the success key, then i go for the rest of the list items

**Comment by turtledude01** [comment]
Not true if the first item is ALWAYS the success
Then theres no reason to check each one out to see if its the success.  And then, all you have to do is drop the first set and then you have the actual data

**Comment by kinggoesgaming** [comment]
but this is something that configurate doesnt understand... in order for me to get the success... i still have to the trigger the iteration... wasting unnecessary time and resources

**Comment by turtledude01** [comment]
Ok, let me try something out then.... But i still dont like the idea of "Payload" being named as such, maybe data?

**Comment by kinggoesgaming** [comment]
sure...
as long as success is separate..

**Comment by turtledude01** [comment]
Ok, let me set up a test for the VERSION check...
